# fswatch spec/main_spec.rb | xargs -n1 -I{} rake spec:device

require_relative '../lib/spell.rb'
require_relative '../lib/available_commands.rb'
require_relative '../lib/activated_spells.rb'
require_relative '../lib/wait.rb'
require_relative '../lib/paralysis.rb'
require_relative '../lib/fast_lightning_bolt.rb'
require_relative '../lib/lightning_bolt.rb'
require_relative '../lib/silence.rb'
require_relative '../lib/ultimate_defense.rb'
require_relative '../lib/shock.rb'
require_relative '../lib/upheaval.rb'
require_relative '../lib/amnesia.rb'
require_relative '../lib/heal.rb'
require_relative '../lib/greater_heal.rb'
require_relative '../lib/counter_spell.rb'
require_relative '../lib/light_wounds.rb'
require_relative '../lib/shield.rb'
require_relative '../lib/reflect.rb'
require_relative '../lib/missile.rb'
require_relative '../lib/seppuku.rb'
require_relative '../lib/heavy_wounds.rb'
require_relative '../lib/sokushi.rb'
require_relative '../lib/next_sequence.rb'
require_relative '../lib/game.rb'
require_relative './game_helper.rb'
